apiVersion: apps/v1
kind: Deployment

metadata:
  name: train-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: train-api

  template:
    metadata:
      labels:
        app: train-api

    spec:
      containers:
        - name: train-api
          image: train-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
            

          readinessProbe:
            httpGet:
                path: /health
                port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10



          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

